Fix crash related to Add Proguard rules for Kotlin Coroutines (#1857)
User reported crash:
```
java.lang.IllegalStateException: Module with the Main
dispatcher is missing. Add dependency providing the
Main dispatcher, e.g. 'kotlinx-coroutines-android'
```

Based on comments in related GitHub ticket,
attempting to see if downgrading
`kotlinx-coroutines` to `1.3.0` [0] and
adding Proguard rules [1] fixes the issue.

[0] https://github.com/Kotlin/kotlinx.coroutines/issues/1532#issuecomment-536299897
[1] https://github.com/Kotlin/kotlinx.coroutines/issues/1532#issue-493167262

Fixes #1856